In [1]:
# 파이토치로 다층 퍼셉트론 구현 
import torch
import torch.nn as nn


In [2]:
# GPU 연산이 가능하다면 Random seed 
torch.manual_seed(777)

# GPU가 사용 가능한가 ? 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

if device == 'cuda' :
    torch.cuda.manual_seed(777)

cpu


In [4]:
# cpu test code
x = [[0,0], [0,1], [1,0], [1,1]]
y = [[0], [1], [1], [0]]

x = torch.tensor(x, dtype = torch.float32).to(device)
y = torch.tensor(y, dtype = torch.float32).to(device)


tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [6]:
# 참고 
# crossEntropy 경우에는 마지막 레이어 노드수가 2개 이상 
# 만약 마지막층 1개 output 이라면 BCELoss 
# BCELoss 사용할경우 마지막 레이어의 값은 0 ~ 1 로 조정 필요
# 마지막 레이어에 시그모이드 함수 적용 


# 다층 퍼셉트론 설계
model = nn.Sequential(
    nn.Linear(2, 10, bias = True), # input 2 hidden 10 
    nn.Sigmoid(),
    nn.Linear(10, 10, bias = True), # input 10 hidden 10 
    nn.Sigmoid(),
    nn.Linear(10, 10, bias = True), # input 10 hidden 10
    nn.Sigmoid(),
    nn.Linear(10, 1, bias = True), # input 10 output = 1 
    
    nn.Sigmoid()
).to(device)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=10, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=10, out_features=10, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=10, out_features=10, bias=True)
  (5): Sigmoid()
  (6): Linear(in_features=10, out_features=1, bias=True)
  (7): Sigmoid()
)


In [9]:
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr= 0.1)

In [15]:
# train loop 
for epoch in range(100001):
    
    optimizer.zero_grad()
    
    output = model(x)
    
    # loss 
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
    
    
    # print
    if epoch % 100 == 0:
        # loss test 
        print(f"epoch {epoch}, loss {loss.item()}")

epoch 0, loss 0.6931343078613281
epoch 100, loss 0.693134069442749
epoch 200, loss 0.6931339502334595
epoch 300, loss 0.6931337118148804
epoch 400, loss 0.6931335926055908
epoch 500, loss 0.6931333541870117
epoch 600, loss 0.6931332349777222
epoch 700, loss 0.6931329965591431
epoch 800, loss 0.693132758140564
epoch 900, loss 0.6931325793266296
epoch 1000, loss 0.6931324005126953
epoch 1100, loss 0.6931322813034058
epoch 1200, loss 0.6931320428848267
epoch 1300, loss 0.6931318640708923
epoch 1400, loss 0.693131685256958
epoch 1500, loss 0.6931314468383789
epoch 1600, loss 0.6931312680244446
epoch 1700, loss 0.6931310892105103
epoch 1800, loss 0.6931309103965759
epoch 1900, loss 0.6931306719779968
epoch 2000, loss 0.6931304931640625
epoch 2100, loss 0.6931302547454834
epoch 2200, loss 0.6931301355361938
epoch 2300, loss 0.6931299567222595
epoch 2400, loss 0.6931297779083252
epoch 2500, loss 0.6931294798851013
epoch 2600, loss 0.693129301071167
epoch 2700, loss 0.6931290626525879
epoch 28

epoch 23100, loss 0.6930268406867981
epoch 23200, loss 0.6930254697799683
epoch 23300, loss 0.6930239796638489
epoch 23400, loss 0.693022608757019
epoch 23500, loss 0.6930209994316101
epoch 23600, loss 0.6930195093154907
epoch 23700, loss 0.6930179595947266
epoch 23800, loss 0.6930163502693176
epoch 23900, loss 0.6930147409439087
epoch 24000, loss 0.693013072013855
epoch 24100, loss 0.6930115222930908
epoch 24200, loss 0.6930097341537476
epoch 24300, loss 0.6930080652236938
epoch 24400, loss 0.6930062174797058
epoch 24500, loss 0.6930044889450073
epoch 24600, loss 0.6930026412010193
epoch 24700, loss 0.6930007934570312
epoch 24800, loss 0.6929987668991089
epoch 24900, loss 0.6929969191551208
epoch 25000, loss 0.6929948925971985
epoch 25100, loss 0.6929928064346313
epoch 25200, loss 0.692990779876709
epoch 25300, loss 0.6929886341094971
epoch 25400, loss 0.6929865479469299
epoch 25500, loss 0.6929843425750732
epoch 25600, loss 0.6929820775985718
epoch 25700, loss 0.6929797530174255
epoc

epoch 45100, loss 0.0020306091755628586
epoch 45200, loss 0.0019807948265224695
epoch 45300, loss 0.0019332526717334986
epoch 45400, loss 0.0018877731636166573
epoch 45500, loss 0.0018442666623741388
epoch 45600, loss 0.0018026281613856554
epoch 45700, loss 0.0017627084162086248
epoch 45800, loss 0.0017244324553757906
epoch 45900, loss 0.0016876804875209928
epoch 46000, loss 0.001652407692745328
epoch 46100, loss 0.0016184347914531827
epoch 46200, loss 0.0015858213882893324
epoch 46300, loss 0.0015543733024969697
epoch 46400, loss 0.0015240904176607728
epoch 46500, loss 0.0014949276810511947
epoch 46600, loss 0.0014667806681245565
epoch 46700, loss 0.0014396343613043427
epoch 46800, loss 0.001413414254784584
epoch 46900, loss 0.001388060161843896
epoch 47000, loss 0.0013635872164741158
epoch 47100, loss 0.0013398908777162433
epoch 47200, loss 0.0013169858139008284
epoch 47300, loss 0.0012947828508913517
epoch 47400, loss 0.0012732666218653321
epoch 47500, loss 0.0012524223420768976
epo

epoch 65700, loss 0.00029519235249608755
epoch 65800, loss 0.0002938657416962087
epoch 65900, loss 0.0002926136658061296
epoch 66000, loss 0.00029133178759366274
epoch 66100, loss 0.00029006481054238975
epoch 66200, loss 0.00028879783349111676
epoch 66300, loss 0.00028756065876223147
epoch 66400, loss 0.0002863234840333462
epoch 66500, loss 0.00028511614073067904
epoch 66600, loss 0.0002839087974280119
epoch 66700, loss 0.0002826716226991266
epoch 66800, loss 0.0002815239131450653
epoch 66900, loss 0.00028034637216478586
epoch 67000, loss 0.0002791688311845064
epoch 67100, loss 0.0002780062204692513
epoch 67200, loss 0.00027685851091519
epoch 67300, loss 0.0002756958710961044
epoch 67400, loss 0.0002745481615420431
epoch 67500, loss 0.0002734302543103695
epoch 67600, loss 0.00027229744591750205
epoch 67700, loss 0.00027119446895085275
epoch 67800, loss 0.000270091462880373
epoch 67900, loss 0.00026898845680989325
epoch 68000, loss 0.00026794508448801935
epoch 68100, loss 0.000266857008

epoch 86300, loss 0.0001527638523839414
epoch 86400, loss 0.00015236144827213138
epoch 86500, loss 0.0001519888755865395
epoch 86600, loss 0.00015163117495831102
epoch 86700, loss 0.0001513033057563007
epoch 86800, loss 0.00015094561967998743
epoch 86900, loss 0.0001505879481555894
epoch 87000, loss 0.00015023026207927614
epoch 87100, loss 0.0001498427736805752
epoch 87200, loss 0.00014949998876545578
epoch 87300, loss 0.00014914230268914253
epoch 87400, loss 0.00014878461661282927
epoch 87500, loss 0.00014847164857201278
epoch 87600, loss 0.00014812886365689337
epoch 87700, loss 0.0001477860932936892
epoch 87800, loss 0.00014742840721737593
epoch 87900, loss 0.00014708562230225652
epoch 88000, loss 0.0001467577531002462
epoch 88100, loss 0.000146414982737042
epoch 88200, loss 0.00014607221237383783
epoch 88300, loss 0.0001457294129068032
epoch 88400, loss 0.0001454164448659867
epoch 88500, loss 0.00014507367450278252
epoch 88600, loss 0.0001447458053007722
epoch 88700, loss 0.00014440

In [17]:
# 학습된 다층 퍼셉트론의 예측값 확인 
with torch.no_grad():
    output = model(x)
    pred = (output > 0.5).float()
    acc = (pred == y).float().mean()
    print("모델의 출력값 \n", output.detach().cpu().numpy())
    print("모델의 예측값 \n", pred.detach().cpu().numpy())
    print("실제값 (Y) \n", y.cpu().numpy())
    print("정확도", acc.item())

모델의 출력값 
 [[8.3187915e-05]
 [9.9987793e-01]
 [9.9988639e-01]
 [1.4005118e-04]]
모델의 예측값 
 [[0.]
 [1.]
 [1.]
 [0.]]
실제값 (Y) 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도 1.0
